# Generated by Django 5.0.4 on 2024-05-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="gpa",
        ),
        migrations.AddField(
            model_name="student",
            name="Fees_status",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
