# Generated by Django 5.0.4 on 2024-05-31 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentapp", "0003_course_profile_student_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="studentapp.course"
            ),
        ),
    ]
