# Generated by Django 5.0.4 on 2024-05-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentapp", "0004_alter_student_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.PositiveIntegerField(),
        ),
    ]
